import 'dotenv/config';
import mongoose from 'mongoose';
import Character from '../models/Character.js';
import Relationship from '../models/Relationship.js';

// ── All 70 characters migrated from mythology-graph.html prototype ──
const characters = [
  { id: 'brahma', label: 'Brahma', type: 'deva', size: 22, filter: 'purana', yuga: 'eternal', sanskrit: 'ब्रह्मा', epithets: ['The Creator', 'Svayambhu', 'Pitamaha'], desc: "Born from a lotus from Vishnu's navel, Brahma shaped all living beings, time, and cosmic law. His four heads recite the four Vedas simultaneously, and from his mind sprang the seven primordial sages.", source: 'Brahma Purāṇa · Vishnu Purāṇa · Mahābhārata' },
  { id: 'vishnu', label: 'Vishnu', type: 'deva', size: 25, filter: 'purana', yuga: 'eternal', sanskrit: 'विष्णु', epithets: ['The Preserver', 'Narayana', 'Hari', 'Chakrapani'], desc: "Reclining on the endless serpent Ananta-Shesha in the primordial ocean, Vishnu sustains cosmic order. He descends as ten principal avatars whenever dharma is endangered — from Matsya the fish to Kalki the future destroyer.", source: 'Vishnu Purāṇa · Bhāgavata Purāṇa · Mahābhārata' },
  { id: 'shiva', label: 'Shiva', type: 'deva', size: 25, filter: 'purana', yuga: 'eternal', sanskrit: 'शिव', epithets: ['Mahadeva', 'Nataraja', 'Neelakantha', 'Pashupatinath'], desc: "The destroyer who dances the Tandava at the end of each cosmic cycle. Shiva meditates on Kailash with matted locks holding the Ganga, a crescent moon at his crown, and a third eye capable of incinerating all creation.", source: 'Shiva Purāṇa · Mahābhārata · Linga Purāṇa' },
  { id: 'indra', label: 'Indra', type: 'deva', size: 17, filter: 'vedic', yuga: 'eternal', sanskrit: 'इन्द्र', epithets: ['Vajrapani', 'Sakra', 'Devendra', 'Purandara'], desc: "King of Svarga and wielder of the thunderbolt Vajra. Commands rain and storms but is repeatedly humbled by mortals and sages — losing his throne, being cursed — making him mythology's most insecure king of gods.", source: 'Rig Veda · Mahābhārata · Rāmāyaṇa' },
  { id: 'surya', label: 'Surya', type: 'deva', size: 15, filter: 'vedic', yuga: 'eternal', sanskrit: 'सूर्य', epithets: ['Vivasvat', 'Ravi', 'Aditya'], desc: "The solar deity who drives his blazing chariot across the sky, nourishing all life. Father of Yama, Karna, Sugriva, and the Ashvins — the most prolific divine father in the epics.", source: 'Rig Veda · Mahābhārata · Surya Purāṇa' },
  { id: 'yama', label: 'Yama', type: 'deva', size: 15, filter: 'purana', yuga: 'eternal', sanskrit: 'यम', epithets: ['Dharmaraja', 'Kala', 'Mrityupati'], desc: "Lord of the dead who judges every soul on the scales of karma, aided by his scribe Chitragupta. The twin of Yami, the first mortal to die. His dialogue with Nachiketa in the Kathopanishad is philosophy's most famous encounter with death.", source: 'Kathopanishad · Mahābhārata · Garuda Purāṇa' },
  { id: 'vayu', label: 'Vayu', type: 'deva', size: 14, filter: 'vedic', yuga: 'eternal', sanskrit: 'वायु', epithets: ['Wind God', 'Pavana', 'Maruta'], desc: "The god of wind, breath, and life-force who pervades all living things. Divine father of Hanuman and Bhima — the two strongest beings in the two great epics.", source: 'Rig Veda · Mahābhārata · Rāmāyaṇa' },
  { id: 'agni', label: 'Agni', type: 'deva', size: 14, filter: 'vedic', yuga: 'eternal', sanskrit: 'अग्नि', epithets: ['Fire God', 'Havyavahana', 'Jataveda'], desc: "The god of sacred fire who carries oblations to the gods and witnesses all sacred rites. The first invoked deity — the Rig Veda's opening word is 'Agni meele purohitam' and the divine witness of every Hindu marriage and yajna.", source: 'Rig Veda · Mahābhārata · Rāmāyaṇa' },
  { id: 'varuna', label: 'Varuna', type: 'deva', size: 13, filter: 'vedic', yuga: 'eternal', sanskrit: 'वरुण', epithets: ['Lord of Oceans', 'Cosmic Law', 'Rta'], desc: "Ancient Vedic god of cosmic order (Rta), moral law, and the seas. He sees all through the stars and punishes oath-breakers. Often invoked alongside Mitra as the twin guardians of sacred law.", source: 'Rig Veda · Atharva Veda · Mahābhārata' },
  { id: 'ganesha', label: 'Ganesha', type: 'deva', size: 19, filter: 'purana', yuga: 'eternal', sanskrit: 'गणेश', epithets: ['Vighneshvara', 'Ganapati', 'Ekadanta'], desc: "The elephant-headed son of Shiva and Parvati, invoked before every endeavor. Ganesha broke off his own tusk to write the Mahabharata as Vyasa dictated, his hand never pausing.", source: 'Ganesha Purāṇa · Shiva Purāṇa · Skanda Purāṇa' },
  { id: 'kartikeya', label: 'Kartikeya', type: 'deva', size: 14, filter: 'purana', yuga: 'eternal', sanskrit: 'कार्तिकेय', epithets: ['Skanda', 'Murugan', 'Shanmukha'], desc: "The six-headed god of war born from Shiva's cosmic seed to destroy the demon Tarakasura. Raised by the six Pleiades star-mothers, he rides a peacock and wields the divine lance Vel.", source: 'Skanda Purāṇa · Shiva Purāṇa · Mahābhārata' },
  { id: 'kubera', label: 'Kubera', type: 'deva', size: 13, filter: 'purana', yuga: 'eternal', sanskrit: 'कुबेर', epithets: ['Lord of Wealth', 'Yaksharaja', 'Dhanapati'], desc: "The pot-bellied god of wealth ruling from golden Alaka on Mount Kailash. Ravana's half-brother who was driven from Lanka when Ravana conquered it.", source: 'Mahābhārata · Rāmāyaṇa · Kubera Purāṇa' },
  { id: 'vishwakarma', label: 'Vishwakarma', type: 'deva', size: 12, filter: 'purana', yuga: 'eternal', sanskrit: 'विश्वकर्मा', epithets: ['Divine Architect', 'Devashilpi'], desc: "The celestial architect who built Dwarka for Krishna, Lanka for Ravana, and forged the weapons of the gods. His skill is so great that he filed away a portion of Surya's blazing light.", source: 'Vishnu Purāṇa · Mahābhārata · Rāmāyaṇa' },
  { id: 'lakshmi', label: 'Lakshmi', type: 'devi', size: 19, filter: 'purana', yuga: 'eternal', sanskrit: 'लक्ष्मी', epithets: ['Shri', 'Kamala', 'Padmavati'], desc: "Goddess of wealth and beauty who arose from the churning of the cosmic ocean, seated on a lotus. As Vishnu's eternal consort, she incarnates beside each avatar — as Sita with Rama, as Radha with Krishna.", source: 'Vishnu Purāṇa · Devi Bhāgavata · Śrī Sūkta' },
  { id: 'parvati', label: 'Parvati', type: 'devi', size: 19, filter: 'purana', yuga: 'eternal', sanskrit: 'पार्वती', epithets: ['Uma', 'Gauri', 'Haimavati', 'Annapurna'], desc: "Daughter of the Himalayas who performed the most rigorous tapas in creation to win Shiva's love after Sati's death. As the primordial Shakti, she manifests as warrior Durga and the terrible Kali.", source: 'Shiva Purāṇa · Devi Māhātmya · Skanda Purāṇa' },
  { id: 'saraswati', label: 'Saraswati', type: 'devi', size: 16, filter: 'vedic', yuga: 'eternal', sanskrit: 'सरस्वती', epithets: ['Vak', 'Sharada', 'Vagdevi'], desc: "Goddess of speech, wisdom, and learning who flows as a sacred river. She holds the veena, scriptures, and rosary — representing sound, knowledge, time, and liberation. Patron of all art and scholarship.", source: 'Rig Veda · Brahma Purāṇa · Saraswati Stotra' },
  { id: 'durga', label: 'Durga', type: 'devi', size: 20, filter: 'purana', yuga: 'eternal', sanskrit: 'दुर्गा', epithets: ['Mahishasura Mardini', 'Amba', 'Bhavani', 'Chandika'], desc: "The invincible warrior goddess assembled from the combined divine light of all gods when none could defeat Mahishasura. Riding a lion with ten weapons from ten gods, Durga is the universe's own defense mechanism.", source: 'Devi Māhātmya · Markandeya Purāṇa · Devi Bhāgavata' },
  { id: 'kali', label: 'Kali', type: 'devi', size: 18, filter: 'purana', yuga: 'eternal', sanskrit: 'काली', epithets: ['Mahakali', 'Bhadrakali', 'Chamunda'], desc: "The ferocious dark goddess born from Durga's forehead in battle. She drank the blood of demon Raktabija before it could spawn more demons. Her necklace of heads and dance on Shiva's chest represent time consuming all creation.", source: "Devi Māhātmya · Kālikā Purāṇa · Mahābhārata" },
  { id: 'sati', label: 'Sati', type: 'devi', size: 14, filter: 'purana', yuga: 'satya', sanskrit: 'सती', epithets: ["Dakshayani", "Shiva's first wife"], desc: "Shiva's first consort who self-immolated when her father Daksha insulted Shiva at a great yajna. Shiva's grief was so devastating he carried her body across the cosmos — Vishnu dismembered it creating the 51 Shakti Peethas.", source: 'Shiva Purāṇa · Devi Bhāgavata · Kalika Purāṇa' },
  { id: 'radha', label: 'Radha', type: 'devi', size: 16, filter: 'purana', yuga: 'dvapara', sanskrit: 'राधा', epithets: ['Radharani', 'Vrindavaneshvari', 'Kishori'], desc: "The supreme devotee of Krishna, representing the soul's longing for the divine. Radha's love for Krishna in the forests of Vrindavan is the original mystical union — pure devotion without ego, celebrated in Jayadeva's Gita Govinda.", source: 'Brahma Vaivarta Purāṇa · Gīta Govinda · Bhāgavata Purāṇa' },
  { id: 'sita', label: 'Sita', type: 'devi', size: 18, filter: 'ramayana', yuga: 'treta', sanskrit: 'सीता', epithets: ['Janaki', 'Vaidehi', 'Bhumija', 'Maithili'], desc: "Daughter of the earth, discovered in a sacred furrow by King Janaka. Her steadfast devotion, endurance through exile and captivity, trial by fire, and final return to the earth make her the most complex heroine of Indian literature.", source: 'Vālmīki Rāmāyaṇa · Rāmcharitmānas · Uttara Rāmāyaṇa' },
  { id: 'draupadi', label: 'Draupadi', type: 'devi', size: 18, filter: 'mahabharata', yuga: 'dvapara', sanskrit: 'द्रौपदी', epithets: ['Panchali', 'Krishnaa', 'Yajnaseni'], desc: "Born from a sacred revenge-fire of King Drupada. Polyandrous wife of all five Pandavas and the moral force of the Mahabharata. Her public humiliation in the Kuru court — where Dushasana attempted to disrobe her — became the war's inescapable cause.", source: 'Mahābhārata · Striparva · Vana Parva' },
  { id: 'mandodari', label: 'Mandodari', type: 'devi', size: 12, filter: 'ramayana', yuga: 'treta', sanskrit: 'मन्दोदरी', epithets: ['Virtuous Queen of Lanka'], desc: "Ravana's most righteous wife who repeatedly warned him to return Sita, foreseeing Lanka's doom. Counted among the five most chaste women of antiquity, her loyalty stands in stark contrast to her husband's fatal pride.", source: 'Vālmīki Rāmāyaṇa · Uttara Kānda' },
  { id: 'ahalya', label: 'Ahalya', type: 'devi', size: 12, filter: 'ramayana', yuga: 'treta', sanskrit: 'अहल्या', epithets: ["The Flawless One", "Brahma's creation"], desc: "Brahma's most perfectly formed creation and wife of Sage Gautama. Indra seduced her in disguise and Gautama cursed her to stone. Her liberation by Rama's touch when he crossed that earth is one of the epics' most celebrated moments of grace.", source: 'Vālmīki Rāmāyaṇa · Bāla Kānda' },
  { id: 'kunti', label: 'Kunti', type: 'devi', size: 15, filter: 'mahabharata', yuga: 'dvapara', sanskrit: 'कुन्ती', epithets: ['Pritha', 'Pandavi', 'Mother of Pandavas'], desc: "Queen-mother who received from Durvasa a mantra to summon any god and bear his child. She bore Karna before marriage and set him on a river — revealed only after his death, making her grief the Mahabharata's most shattering maternal tragedy.", source: 'Mahābhārata · Adi Parva · Stri Parva' },
  { id: 'gandhari', label: 'Gandhari', type: 'devi', size: 14, filter: 'mahabharata', yuga: 'dvapara', sanskrit: 'गान्धारी', epithets: ['Princess of Gandhara'], desc: "Queen who blindfolded herself for life upon marrying the blind Dhritarashtra. She bore 101 children from a single mass of flesh divided by Vyasa. At the war's end she cursed Krishna that his entire Yadava clan would destroy itself — which it did.", source: 'Mahābhārata · Adi Parva · Stri Parva' },
  { id: 'rama', label: 'Rama', type: 'deva', size: 24, filter: 'ramayana', yuga: 'treta', sanskrit: 'राम', epithets: ['Maryada Purushottam', 'Raghava', 'Ramachandra'], desc: "The seventh avatar of Vishnu and ideal king of Ayodhya. His fourteen-year forest exile with Sita and Lakshmana, war against Ravana, and unwavering adherence to dharma — even at personal cost — make him the template of the perfect human being.", source: 'Vālmīki Rāmāyaṇa · Adhyātma Rāmāyaṇa · Rāmcharitmānas' },
  { id: 'lakshmana', label: 'Lakshmana', type: 'hero', size: 16, filter: 'ramayana', yuga: 'treta', sanskrit: 'लक्ष्मण', epithets: ['Saumitri', 'Ramanuja', 'Sheshavatara'], desc: "Rama's devoted younger brother, incarnation of the cosmic serpent Shesha. He forsook kingdom and comfort for all fourteen years of exile. When he fell in battle, Hanuman flew to the Himalayas for the herb Sanjeevani.", source: 'Vālmīki Rāmāyaṇa · Uttara Kānda' },
  { id: 'hanuman', label: 'Hanuman', type: 'deva', size: 22, filter: 'ramayana', yuga: 'treta', sanskrit: 'हनुमान', epithets: ['Mahavira', 'Anjaneya', 'Bajrangbali', 'Maruti'], desc: "Son of Vayu and the greatest devotee of Rama. Leapt 800 miles across the ocean to Lanka, found Sita, burned Ravana's city, and carried the Dronagiri mountain of healing herbs. Said to be immortal, still present wherever Rama's name is spoken.", source: 'Vālmīki Rāmāyaṇa · Sundara Kānda · Hanuman Chālīsā' },
  { id: 'ravana', label: 'Ravana', type: 'asura', size: 21, filter: 'ramayana', yuga: 'treta', sanskrit: 'रावण', epithets: ['Dashamukha', 'Lankapati', 'Paulastya'], desc: "The ten-headed demon king of Lanka — a master of the Vedas, composer of the Shiva Tandava Stotram, and devotee of Shiva who nevertheless let pride and lust destroy a golden civilization. He forgot to mention humans when requesting his boon of invulnerability from gods and demons.", source: 'Vālmīki Rāmāyaṇa · Uttara Kānda · Lanka Kānda' },
  { id: 'vibhishana', label: 'Vibhishana', type: 'hero', size: 13, filter: 'ramayana', yuga: 'treta', sanskrit: 'विभीषण', epithets: ['Dharmatma', 'Lankeshvara'], desc: "Ravana's youngest brother, the only voice of conscience in Lanka. Expelled for urging the return of Sita, he surrendered to Rama, revealed Ravana's secret weakness, and was crowned Lanka's righteous king after the war.", source: 'Vālmīki Rāmāyaṇa · Lanka Kānda' },
  { id: 'sugriva', label: 'Sugriva', type: 'hero', size: 13, filter: 'ramayana', yuga: 'treta', sanskrit: 'सुग्रीव', epithets: ['Monkey King', 'Son of Surya'], desc: "The monkey king of Kishkindha, son of Surya. Exiled by his brother Vali who usurped throne and wife, Sugriva allied with Rama who killed Vali. He then commanded the great monkey army in the march to Lanka.", source: 'Vālmīki Rāmāyaṇa · Kishkindha Kānda' },
  { id: 'vali', label: 'Vali', type: 'hero', size: 12, filter: 'ramayana', yuga: 'treta', sanskrit: 'वाली', epithets: ['Monkey King', 'Son of Indra'], desc: "The mighty monkey king of Kishkindha who received a boon that half his opponent's strength would flow to him in battle. Killed by Rama from behind a tree — a morally contested act that Rama himself had to justify.", source: 'Vālmīki Rāmāyaṇa · Kishkindha Kānda' },
  { id: 'jatayu', label: 'Jatayu', type: 'celestial', size: 11, filter: 'ramayana', yuga: 'treta', sanskrit: 'जटायु', epithets: ["Vulture King", "Rama's Protector"], desc: "The aged eagle king who battled Ravana to protect Sita despite being outmatched. Ravana severed his wings, but Jatayu survived just long enough to tell Rama which direction Sita had been taken. Rama performed his last rites as a son would.", source: 'Vālmīki Rāmāyaṇa · Aranya Kānda' },
  { id: 'krishna', label: 'Krishna', type: 'deva', size: 24, filter: 'mahabharata', yuga: 'dvapara', sanskrit: 'कृष्ण', epithets: ['Govinda', 'Madhava', 'Parthasarathi', 'Murlidhar'], desc: "The eighth avatar of Vishnu — divine cowherd, philosopher-king, and warrior-diplomat. His counsel to Arjuna on the Kurukshetra battlefield became the Bhagavad Gita, history's most celebrated dialogue on duty, action, and the nature of the self.", source: 'Mahābhārata · Bhāgavata Purāṇa · Harivamsha' },
  { id: 'arjuna', label: 'Arjuna', type: 'hero', size: 21, filter: 'mahabharata', yuga: 'dvapara', sanskrit: 'अर्जुन', epithets: ['Partha', 'Dhananjaya', 'Savyasachi', 'Gandivadhari'], desc: "The greatest archer of his age, son of Indra. His existential crisis on the battlefield of Kurukshetra prompted Krishna's Bhagavad Gita. He won Draupadi at her swayamvara, spent a year as the eunuch Brihannala, and felled the grandsire Bhishma.", source: 'Mahābhārata · Bhagavad Gītā' },
  { id: 'karna', label: 'Karna', type: 'hero', size: 20, filter: 'mahabharata', yuga: 'dvapara', sanskrit: 'कर्ण', epithets: ['Radheya', 'Vasusena', 'Daanveer', 'Suryaputra'], desc: "Born to Kunti from the sun god before her marriage and abandoned in a basket on the river. Despite divine armor and earrings at birth, he was denied education, mocked as low-born, cursed by his guru — yet remained history's greatest giver, never refusing anyone at his door.", source: 'Mahābhārata · Karna Parva · Shanti Parva' },
  { id: 'yudhishthira', label: 'Yudhishthira', type: 'hero', size: 16, filter: 'mahabharata', yuga: 'dvapara', sanskrit: 'युधिष्ठिर', epithets: ['Dharmaraja', 'Ajatashatru'], desc: "Eldest Pandava, son of Yama, renowned as the most dharmic man of his age. Yet his addiction to dice — where he staked his brothers, wife, and himself — set the Kurukshetra war in motion. His final test involved refusing to enter heaven without his loyal dog.", source: 'Mahābhārata · Sabha Parva · Svargarohanika Parva' },
  { id: 'bhima', label: 'Bhima', type: 'hero', size: 16, filter: 'mahabharata', yuga: 'dvapara', sanskrit: 'भीम', epithets: ['Vrikodara', 'Bhimasena', 'Pavansuta'], desc: "The second Pandava, son of Vayu, with extraordinary strength matched by fierce loyalty. He slew Hidimba, Bakasura, Kichaka, Jarasandha, and all hundred Kauravas — crushing Duryodhana's thigh with his mace as Bhishma had forbidden.", source: 'Mahābhārata · Bhima Parva' },
  { id: 'duryodhana', label: 'Duryodhana', type: 'hero', size: 17, filter: 'mahabharata', yuga: 'dvapara', sanskrit: 'दुर्योधन', epithets: ['Suyodhana', 'Kuruvamshi'], desc: "The eldest Kaurava, trained by Balarama and a supreme mace-fighter. His refusal to part with even a needle's point of land for the Pandavas, driven by envy and wounded pride, turned Hastinapura's court into the kindling for the greatest war in mythology.", source: 'Mahābhārata · Sabha Parva · Shalya Parva' },
  { id: 'bhishma', label: 'Bhishma', type: 'hero', size: 18, filter: 'mahabharata', yuga: 'dvapara', sanskrit: 'भीष्म', epithets: ['Pitamaha', 'Devavrata', 'Gangaputra'], desc: "Son of the river goddess Ganga who took the terrible vow of eternal celibacy so his father could remarry — earning the name Bhishma (the terrible vow). Blessed with choosing his own death, he fought ten days for the Kauravas despite knowing the Pandavas were right.", source: 'Mahābhārata · Bhishma Parva · Shanti Parva' },
  { id: 'ashvatthama', label: 'Ashvatthama', type: 'hero', size: 14, filter: 'mahabharata', yuga: 'dvapara', sanskrit: 'अश्वत्थामा', epithets: ["Drona's Son", "The Immortal Cursed"], desc: "Son of Drona and partial incarnation of Shiva. After Drona's death, he unleashed terrible weapons in rage. Krishna cursed him to wander the earth immortal, bleeding from his forehead, shunned by all — one of mythology's rare immortal wanderers.", source: 'Mahābhārata · Sauptika Parva' },
  { id: 'nakula', label: 'Nakula', type: 'hero', size: 11, filter: 'mahabharata', yuga: 'dvapara', sanskrit: 'नकुल', epithets: ['Twin Ashvin', 'Handsome Pandava'], desc: "The fourth Pandava, son of the divine physician Nasatya. Considered the most handsome man of his age and an expert horse-trainer. During the year of disguise he served as royal horse-keeper in King Virata's court.", source: 'Mahābhārata' },
  { id: 'sahadeva', label: 'Sahadeva', type: 'hero', size: 11, filter: 'mahabharata', yuga: 'dvapara', sanskrit: 'सहदेव', epithets: ['Twin Ashvin', 'Sage Among Warriors'], desc: "The youngest Pandava, twin of Nakula. Sahadeva possessed complete knowledge of past, present, and future — a gift he was cursed to never share unless asked. He is said to have known the entire war's outcome before it began.", source: 'Mahābhārata' },
  { id: 'dhritarashtra', label: 'Dhritarashtra', type: 'hero', size: 13, filter: 'mahabharata', yuga: 'dvapara', sanskrit: 'धृतराष्ट्र', epithets: ['Blind King', 'Kuru King'], desc: "The blind king of Hastinapura who knew his son Duryodhana was wrong at every moral crossroads but could never bring himself to oppose him. His portrait of parental love corrupting justice is the Mahabharata's saddest failure.", source: 'Mahābhārata · Sabha Parva · Udyoga Parva' },
  { id: 'ekalavya', label: 'Ekalavya', type: 'hero', size: 12, filter: 'mahabharata', yuga: 'dvapara', sanskrit: 'एकलव्य', epithets: ['Self-taught Archer', 'Nishadha Prince'], desc: "The tribal prince who taught himself archery before a clay idol of Drona, surpassing all students. When discovered, Drona demanded his right thumb as guru-dakshina — instantly crippling history's finest self-taught archer. The sharpest critique of caste in the epics.", source: 'Mahābhārata · Adi Parva' },
  { id: 'vyasa', label: 'Vyasa', type: 'sage', size: 18, filter: 'mahabharata', yuga: 'dvapara', sanskrit: 'व्यास', epithets: ['Veda Vyasa', 'Krishna Dvaipayana', 'Badarayana'], desc: "The sage who arranged the four Vedas, authored the Mahabharata (the longest poem ever written), composed all eighteen Puranas, and the Brahma Sutras. Simultaneously the story's author, narrator, and a participant as grandfather of both Pandavas and Kauravas.", source: 'Mahābhārata · Vishnu Purāṇa · Brahma Purāṇa' },
  { id: 'valmiki', label: 'Valmiki', type: 'sage', size: 15, filter: 'ramayana', yuga: 'treta', sanskrit: 'वाल्मीकि', epithets: ['Adikavi', 'First Poet'], desc: "A reformed bandit transformed by Narada's teaching who became the first Sanskrit poet. On seeing a hunter kill one bird of a mating pair, grief burst from him as the first shloka in all human literature. Brahma commanded him to write the entire Ramayana in that form.", source: 'Vālmīki Rāmāyaṇa · Uttara Kānda' },
  { id: 'narada', label: 'Narada', type: 'sage', size: 15, filter: 'purana', yuga: 'eternal', sanskrit: 'नारद', epithets: ['Devarshi', 'Cosmic Wanderer', 'Trilokacharya'], desc: 'The wandering celestial sage who travels the three worlds with his veena, chanting "Narayan." A divine provocateur who plants seeds of conflict and devotion — he inspired the Ramayana, guided Prahlada, and stands as the prototype of the journalist-sage.', source: 'Mahābhārata · Vishnu Purāṇa · Nārada Purāṇa' },
  { id: 'vishwamitra', label: 'Vishwamitra', type: 'sage', size: 15, filter: 'ramayana', yuga: 'treta', sanskrit: 'विश्वामित्र', epithets: ['Kaushika', 'Brahmarshi', 'Gayatri Seer'], desc: "A warrior king who transformed himself from Kshatriya to Brahmarshi through grueling austerities. He trained Rama and Lakshmana and is the seer of the Gayatri mantra.", source: 'Vālmīki Rāmāyaṇa · Mahābhārata · Bāla Kānda' },
  { id: 'vasishtha', label: 'Vasishtha', type: 'sage', size: 14, filter: 'ramayana', yuga: 'treta', sanskrit: 'वसिष्ठ', epithets: ['Brahmarshi', 'Raj Guru of Ayodhya'], desc: "The celebrated sage and family guru of Ayodhya's solar dynasty. His rivalry with Vishwamitra defines an arc of Vedic literature. His divine cow Nandini could fulfill any wish.", source: 'Vālmīki Rāmāyaṇa · Yoga Vasishtha · Adi Parva' },
  { id: 'agastya', label: 'Agastya', type: 'sage', size: 14, filter: 'purana', yuga: 'treta', sanskrit: 'अगस्त्य', epithets: ['Pitcherman', 'Father of Tamil Literature'], desc: "The sage who drank the ocean to expose demons and subdued the Vindhya mountains. He gave Rama the Aditya Hridayam before the final battle with Ravana.", source: 'Rāmāyaṇa · Mahābhārata · Padma Purāṇa' },
  { id: 'parashurama', label: 'Parashurama', type: 'avatar', size: 16, filter: 'purana', yuga: 'treta', sanskrit: 'परशुराम', epithets: ['Sixth Avatar', 'Brahmin Warrior', 'Jamadagnya', 'Chiranjivi'], desc: "The sixth avatar of Vishnu and a Chiranjivi. An immortal Brahmin-warrior who remains on earth in penance on Mount Mahendra, waiting to train the final avatar Kalki.", source: 'Mahābhārata · Vishnu Purāṇa · Bhāgavata Purāṇa' },
  { id: 'durvasa', label: 'Durvasa', type: 'sage', size: 13, filter: 'purana', yuga: 'eternal', sanskrit: 'दुर्वासा', epithets: ['Hot-tempered Sage', 'Shiva incarnation'], desc: "The most feared sage in the three worlds — a partial incarnation of Shiva whose curses were as powerful as his blessings. He gave Kunti her divine mantra.", source: 'Mahābhārata · Bhāgavata Purāṇa · Vishnu Purāṇa' },
  { id: 'hiranyakashipu', label: 'Hiranyakashipu', type: 'asura', size: 17, filter: 'purana', yuga: 'satya', sanskrit: 'हिरण्यकशिपु', epithets: ['King of Asuras'], desc: "The demon king who declared himself God and forbade Vishnu worship. He was destroyed by the fourth avatar Narasimha to protect the child-devotee Prahlada.", source: 'Bhāgavata Purāṇa · Vishnu Purāṇa' },
  { id: 'prahlada', label: 'Prahlada', type: 'hero', size: 14, filter: 'purana', yuga: 'satya', sanskrit: 'प्रह्लाद', epithets: ["Maha-Bhakta", "Vishnu's Beloved"], desc: "The child-devotee of Vishnu who remained unshaken in faith despite his father Hiranyakashipu's persecution. He represents the archetype of pure devotion.", source: 'Bhāgavata Purāṇa · Narasimha Purāṇa' },
  { id: 'mahishasura', label: 'Mahishasura', type: 'asura', size: 16, filter: 'purana', yuga: 'satya', sanskrit: 'महिषासुर', epithets: ['Buffalo Demon'], desc: "The shape-shifting buffalo demon who conquered the three worlds after receiving a boon from Brahma. He was finally defeated by the warrior goddess Durga.", source: 'Devi Māhātmya · Markandeya Purāṇa' },
  { id: 'bali', label: 'King Bali', type: 'asura', size: 14, filter: 'purana', yuga: 'treta', sanskrit: 'बलि', epithets: ['Mahabali', 'Virtuous Asura King'], desc: "The righteous demon king who ruled the three worlds. Vishnu as Vamana pushed him to the netherworld but granted him immortality as a mark of respect.", source: 'Bhāgavata Purāṇa · Vamana Purāṇa' },
  { id: 'tarakasura', label: 'Tarakasura', type: 'asura', size: 14, filter: 'purana', yuga: 'satya', sanskrit: 'तारकासुर', epithets: ['Demon of Obstacles'], desc: "The demon who could only be killed by Shiva's son. He was finally destroyed by Kartikeya, the god of war born from Shiva's divine seed.", source: 'Skanda Purāṇa · Shiva Purāṇa' },
  { id: 'kumbhakarna', label: 'Kumbhakarna', type: 'asura', size: 14, filter: 'ramayana', yuga: 'treta', sanskrit: 'कुम्भकर्ण', epithets: ["The Giant Sleeper", "Ravana's Brother"], desc: "Ravana's giant brother who slept for six months at a time. Though righteous at heart, he fought for his family and was slain by Rama.", source: 'Vālmīki Rāmāyaṇa · Yuddha Kānda' },
  { id: 'vritra', label: 'Vritra', type: 'asura', size: 13, filter: 'vedic', yuga: 'satya', sanskrit: 'वृत्र', epithets: ['The Enveloper', 'Drought Serpent'], desc: "The primordial serpentine demon of drought who swallowed the world's waters. He was shattered by Indra's Vajra thunderbolt to release the rivers.", source: 'Rig Veda · Mahābhārata · Bhāgavata Purāṇa' },
  { id: 'shishupala', label: 'Shishupala', type: 'asura', size: 12, filter: 'mahabharata', yuga: 'dvapara', sanskrit: 'शिशुपाल', epithets: ['King of Chedi', 'Jaya reborn'], desc: "King of Chedi who exhausted a hundred pardons from Krishna before being slain by the Sudarshana Chakra at Yudhishthira's coronation.", source: 'Mahābhārata · Sabha Parva' },
  { id: 'garuda', label: 'Garuda', type: 'celestial', size: 15, filter: 'purana', yuga: 'eternal', sanskrit: 'गरुड़', epithets: ['King of Birds', 'Nagantaka'], desc: "The divine eagle and vehicle of Vishnu. Born of sage Kashyapa and Vinata, he is the eternal enemy of the Nagas and the thief of Amrita.", source: 'Mahābhārata · Garuda Purāṇa · Vishnu Purāṇa' },
  { id: 'nandi', label: 'Nandi', type: 'celestial', size: 12, filter: 'purana', yuga: 'eternal', sanskrit: 'नन्दी', epithets: ["Shiva's Bull", 'Gatekeeper of Kailash'], desc: "The sacred bull and chief attendant of Shiva. He guards the threshold of Kailash and is the primary listener of Shiva's cosmic wisdom.", source: 'Shiva Purāṇa · Skanda Purāṇa' },
  { id: 'menaka', label: 'Menaka', type: 'celestial', size: 12, filter: 'purana', yuga: 'eternal', sanskrit: 'मेनका', epithets: ['Chief Apsara'], desc: "The most beautiful apsara sent by Indra to break Vishwamitra's tapas. She succeeded and bore Shakuntala before departing back to heaven.", source: 'Mahābhārata · Adi Parva' },
  { id: 'urvashi', label: 'Urvashi', type: 'celestial', size: 11, filter: 'purana', yuga: 'eternal', sanskrit: 'उर्वशी', epithets: ['Jewel of Apsaras'], desc: "The celebrated apsara born from Vishnu's thigh. She cursed Arjuna to be a eunuch, which became a vital cover for the Pandavas' year of disguise.", source: 'Mahābhārata · Vana Parva' },
  { id: 'shakuntala', label: 'Shakuntala', type: 'hero', size: 12, filter: 'mahabharata', yuga: 'dvapara', sanskrit: 'शकुन्तला', epithets: ['Forest Girl', "Bharata's mother"], desc: "Daughter of Menaka and Vishwamitra, raised by sage Kanva. Her marriage to King Dushyanta and the birth of Bharata gave India its original name.", source: 'Mahābhārata · Adi Parva · Abhijnanashakuntalam' },
  { id: 'narasimha', label: 'Narasimha', type: 'avatar', size: 16, filter: 'purana', yuga: 'satya', sanskrit: 'नरसिंह', epithets: ['Man-Lion', 'Fourth Avatar'], desc: "The half-man, half-lion fourth avatar of Vishnu who emerged from a palace pillar at dusk to destroy Hiranyakashipu and restore dharma.", source: 'Bhāgavata Purāṇa · Narasimha Purāṇa' },
  { id: 'drona', label: 'Drona', type: 'sage', size: 16, filter: 'mahabharata', yuga: 'dvapara', sanskrit: 'द्रोण', epithets: ['Dronacharya', 'Royal Preceptor'], desc: "The Brahmin master of warfare who trained the Kuru princes. His demand for Ekalavya's thumb remains the epics' most controversial act of institutional power.", source: 'Mahābhārata · Drona Parva · Adi Parva' },
  // Dashavatara Expansion
  { id: 'matsya', label: 'Matsya', type: 'avatar', size: 15, filter: 'purana', yuga: 'satya', sanskrit: 'मत्स्य', epithets: ['The Fish Avatar', 'First Avatar'], desc: "Vishnu's first avatar, a fish who saved Manu and the seven sages from the cosmic deluge. He guided the ship containing all life to safety.", source: 'Matsya Purāṇa · Bhāgavatam' },
  { id: 'kurma', label: 'Kurma', type: 'avatar', size: 15, filter: 'purana', yuga: 'satya', sanskrit: 'कूर्म', epithets: ['The Tortoise Avatar', 'Second Avatar'], desc: "The second avatar, a tortoise who supported Mount Mandara on his back during the Churning of the Ocean to prevent it from sinking into the abyss.", source: 'Kurma Purāṇa · Vishnu Purāṇa' },
  { id: 'varaha', label: 'Varaha', type: 'avatar', size: 15, filter: 'purana', yuga: 'satya', sanskrit: 'वराह', epithets: ['The Boar Avatar', 'Third Avatar'], desc: "The third avatar, a cosmic boar who lifted the Earth (Bhudevi) from the bottom of the primordial ocean where the demon Hiranyaksha had hidden her.", source: 'Varaha Purāṇa · Bhāgavata Purāṇa' },
  { id: 'vamana', label: 'Vamana', type: 'avatar', size: 15, filter: 'purana', yuga: 'treta', sanskrit: 'वामन', epithets: ['The Dwarf Avatar', 'Fifth Avatar'], desc: "The fifth avatar who appeared as a young Brahmin dwarf to reclaim the three worlds from the righteous asura King Bali in three mystical paces.", source: 'Vamana Purāṇa · Bhāgavata Purāṇa' },
  { id: 'balarama', label: 'Balarama', type: 'avatar', size: 16, filter: 'purana', yuga: 'dvapara', sanskrit: 'बलराम', epithets: ['Haladhara', 'Sankarshana', 'Eighth Avatar'], desc: "Elder brother of Krishna and incarnation of the serpent Shesha. A master of the mace and plow, representing pure strength and divine support.", source: 'Mahābhārata · Bhāgavata Purāṇa' },
  { id: 'kalki', label: 'Kalki', type: 'avatar', size: 18, filter: 'purana', yuga: 'kali', sanskrit: 'कलियुग', epithets: ['The Final Avatar'], desc: "The future tenth avatar who will appear at the turn of the cosmic cycle on a white horse to destroy darkness and herald the return of Satya Yuga.", source: 'Kalki Purāṇa · Vishnu Purāṇa' },
  // Devi expansion
  { id: 'mahakali', label: 'Mahakali', type: 'devi', size: 22, filter: 'purana', yuga: 'eternal', sanskrit: 'महाकाली', epithets: ['Supreme Dark Goddess'], desc: "The cosmic form of Kali representing Time that consumes all creation. She is the primordial energy that existed before the universe and will remain after.", source: 'Devi Māhātmya · Kālikā Purāṇa' },
  { id: 'chamunda', label: 'Chamunda', type: 'devi', size: 17, filter: 'purana', yuga: 'eternal', sanskrit: 'चामुण्डा', epithets: ['Slayer of Chanda and Munda'], desc: "The fierce dark goddess who emerged from Durga's brow to destroy the demon generals. She represents the terrifying power that annihilates internal enemies like ego.", source: 'Devi Māhātmya · Markandeya Purāṇa' },
  { id: 'tripura_sundari', label: 'Tripura Sundari', type: 'devi', size: 19, filter: 'purana', yuga: 'eternal', sanskrit: 'त्रिपुर सुन्दरी', epithets: ['Lalita', 'Empress of the Three Worlds'], desc: "The supreme goddess of Sri Vidya. She represents the highest beauty and cosmic intelligence presiding over the waking, dreaming, and deep sleep states.", source: 'Lalitā Sahasranāma · Brahmāṇḍa Purāṇa' },
  // Chiranjivi & Others
  { id: 'ashwatthama', label: 'Ashwatthama', type: 'hero', size: 14, filter: 'mahabharata', yuga: 'eternal', sanskrit: 'अश्वत्थामा', epithets: ["Drona's Son", "The Cursed Immortal"], desc: "A great warrior and a Chiranjivi. Cursed by Krishna after the war to wander the earth with an unhealing wound, shunned by humans until the end of time.", source: 'Mahābhārata · Sauptika Parva' },
  { id: 'kripacharya', label: 'Kripacharya', type: 'sage', size: 13, filter: 'mahabharata', yuga: 'eternal', sanskrit: 'कृपाचार्य', epithets: ['Royal Tutor', 'Chiranjivi'], desc: "One of the seven immortals and a surviving master of the Kurukshetra war. He remains on earth as a silent witness and teacher for future generations.", source: 'Mahābhārata · Adi Parva' },
  { id: 'markandeya', label: 'Markandeya', type: 'sage', size: 14, filter: 'purana', yuga: 'eternal', sanskrit: 'मार्कण्डेय', epithets: ['Death-conquering Sage', 'Chiranjivi'], desc: "The sage who conquered death by clinging to the Shiva Linga. He is a Chiranjivi who has witnessed the rise and fall of multiple cosmic cycles.", source: 'Markandeya Purāṇa · Bhāgavata Purāṇa' },
  { id: 'shuka', label: 'Shuka', type: 'sage', size: 14, filter: 'purana', yuga: 'dvapara', sanskrit: 'शुक', epithets: ['Enlightened One', 'Vyasa-putra'], desc: "The enlightened son of Vyasa who narrated the Bhagavatam. He was born with divine knowledge and represents the highest level of spiritual attainment.", source: 'Bhāgavata Purāṇa · Devi Bhāgavata' },
  { id: 'savitri', label: 'Savitri', type: 'devi', size: 13, filter: 'purana', yuga: 'treta', sanskrit: 'सावित्री', epithets: ['The Chaste One'], desc: "The princess who outwitted Yama through her wisdom and devotion, successfully reclaiming her husband Satyavan from the clutches of Death.", source: 'Mahābhārata · Vana Parva' },
  { id: 'hidimba', label: 'Hidimba', type: 'asura', size: 12, filter: 'mahabharata', yuga: 'dvapara', sanskrit: 'हिडिम्बा', epithets: ["Bhima's Wife"], desc: "The forest rakshasi who married Bhima and bore him Ghatotkacha. She represents the ancient integration of tribal culture into the epic fabric.", source: 'Mahābhārata · Adi Parva' },
];

// ── All 200+ relationships ──
const relationships = [
  { source: 'brahma', target: 'vishnu', label: 'Trinity', type: 'divine' },
  { source: 'vishnu', target: 'shiva', label: 'Trinity', type: 'divine' },
  { source: 'brahma', target: 'shiva', label: 'Trinity', type: 'divine' },
  { source: 'vishnu', target: 'brahma', label: 'Creator of', type: 'divine' },
  { source: 'brahma', target: 'saraswati', label: 'Consort', type: 'family' },
  { source: 'vishnu', target: 'lakshmi', label: 'Consort', type: 'family' },
  { source: 'shiva', target: 'parvati', label: 'Consort', type: 'family' },
  { source: 'parvati', target: 'shiva', label: 'Devoted Wife', type: 'family' },
  { source: 'shiva', target: 'sati', label: 'First Consort', type: 'family' },
  { source: 'sati', target: 'parvati', label: 'Reborn as', type: 'divine' },
  { source: 'shiva', target: 'ganesha', label: 'Father', type: 'family' },
  { source: 'shiva', target: 'kartikeya', label: 'Father', type: 'family' },
  { source: 'parvati', target: 'ganesha', label: 'Mother', type: 'family' },
  { source: 'parvati', target: 'kartikeya', label: 'Mother', type: 'family' },
  { source: 'parvati', target: 'durga', label: 'Manifestation of', type: 'divine' },
  { source: 'durga', target: 'kali', label: 'Born from', type: 'divine' },
  { source: 'durga', target: 'chamunda', label: 'Form of', type: 'divine' },
  { source: 'durga', target: 'mahakali', label: 'Supreme Form', type: 'divine' },
  { source: 'durga', target: 'tripura_sundari', label: 'Cosmic Form', type: 'divine' },
  { source: 'vishnu', target: 'matsya', label: 'Manifestation of', type: 'manifestation' },
  { source: 'vishnu', target: 'kurma', label: 'Manifestation of', type: 'manifestation' },
  { source: 'vishnu', target: 'varaha', label: 'Manifestation of', type: 'manifestation' },
  { source: 'vishnu', target: 'narasimha', label: 'Manifestation of', type: 'manifestation' },
  { source: 'vishnu', target: 'vamana', label: 'Manifestation of', type: 'manifestation' },
  { source: 'vishnu', target: 'parashurama', label: 'Manifestation of', type: 'manifestation' },
  { source: 'vishnu', target: 'rama', label: 'Manifestation of', type: 'manifestation' },
  { source: 'vishnu', target: 'krishna', label: 'Manifestation of', type: 'manifestation' },
  { source: 'vishnu', target: 'balarama', label: 'Manifestation of', type: 'manifestation' },
  { source: 'vishnu', target: 'kalki', label: 'Manifestation of', type: 'manifestation' },
  { source: 'vishnu', target: 'bali', label: 'Vamana defeats', type: 'conflict' },
  { source: 'varaha', target: 'hiranyakashipu', label: 'Brother of Hiranyaksha', type: 'conflict' },
  { source: 'vishnu', target: 'garuda', label: 'Vehicle', type: 'divine' },
  { source: 'shiva', target: 'nandi', label: 'Vehicle', type: 'divine' },
  { source: 'lakshmi', target: 'sita', label: 'Avatar', type: 'divine' },
  { source: 'lakshmi', target: 'radha', label: 'Avatar', type: 'divine' },
  { source: 'surya', target: 'yama', label: 'Father', type: 'family' },
  { source: 'surya', target: 'karna', label: 'Father', type: 'family' },
  { source: 'surya', target: 'sugriva', label: 'Father', type: 'family' },
  { source: 'vayu', target: 'hanuman', label: 'Father', type: 'family' },
  { source: 'vayu', target: 'bhima', label: 'Father', type: 'family' },
  { source: 'indra', target: 'arjuna', label: 'Father', type: 'family' },
  { source: 'indra', target: 'vali', label: 'Father', type: 'family' },
  { source: 'indra', target: 'ahalya', label: 'Seduces', type: 'conflict' },
  { source: 'indra', target: 'karna', label: 'Stripped cosmic armor', type: 'conflict' },
  { source: 'rama', target: 'sita', label: 'Husband', type: 'family' },
  { source: 'rama', target: 'lakshmana', label: 'Brother', type: 'family' },
  { source: 'hanuman', target: 'rama', label: 'Supreme Devotee of', type: 'divine' },
  { source: 'hanuman', target: 'sita', label: 'Found & Rescued', type: 'alliance' },
  { source: 'rama', target: 'ravana', label: 'Enemies', type: 'conflict' },
  { source: 'rama', target: 'kumbhakarna', label: 'Slays', type: 'conflict' },
  { source: 'ravana', target: 'sita', label: 'Abducts', type: 'conflict' },
  { source: 'ravana', target: 'shiva', label: 'Supreme Devotee of', type: 'divine' },
  { source: 'ravana', target: 'vibhishana', label: 'Brother', type: 'family' },
  { source: 'ravana', target: 'kumbhakarna', label: 'Brother', type: 'family' },
  { source: 'ravana', target: 'mandodari', label: 'Husband', type: 'family' },
  { source: 'ravana', target: 'kubera', label: 'Half-brother', type: 'family' },
  { source: 'ravana', target: 'nandi', label: 'Cursed by', type: 'conflict' },
  { source: 'sugriva', target: 'vali', label: 'Brother', type: 'family' },
  { source: 'rama', target: 'sugriva', label: 'Allied with', type: 'alliance' },
  { source: 'rama', target: 'vibhishana', label: 'Allied with', type: 'alliance' },
  { source: 'hanuman', target: 'sugriva', label: 'Serves', type: 'alliance' },
  { source: 'vishwamitra', target: 'rama', label: 'Guru', type: 'guru' },
  { source: 'vasishtha', target: 'rama', label: 'Family Guru', type: 'guru' },
  { source: 'valmiki', target: 'sita', label: 'Sheltered', type: 'divine' },
  { source: 'narada', target: 'valmiki', label: 'Inspired', type: 'divine' },
  { source: 'agastya', target: 'rama', label: 'Gave Aditya Hridayam', type: 'divine' },
  { source: 'jatayu', target: 'sita', label: 'Died protecting', type: 'divine' },
  { source: 'jatayu', target: 'ravana', label: 'Fought', type: 'conflict' },
  { source: 'menaka', target: 'vishwamitra', label: 'Seduces', type: 'conflict' },
  { source: 'menaka', target: 'shakuntala', label: 'Mother', type: 'family' },
  { source: 'vishwamitra', target: 'shakuntala', label: 'Father', type: 'family' },
  { source: 'urvashi', target: 'arjuna', label: 'Curses', type: 'conflict' },
  { source: 'krishna', target: 'arjuna', label: 'Charioteer', type: 'divine' },
  { source: 'krishna', target: 'balarama', label: 'Brother', type: 'family' },
  { source: 'arjuna', target: 'krishna', label: 'Devotee & Friend of', type: 'alliance' },
  { source: 'krishna', target: 'radha', label: 'Divine Love', type: 'family' },
  { source: 'krishna', target: 'draupadi', label: 'Divine Protector of', type: 'alliance' },
  { source: 'krishna', target: 'shishupala', label: 'Slays', type: 'conflict' },
  { source: 'arjuna', target: 'karna', label: 'Rivals', type: 'conflict' },
  { source: 'arjuna', target: 'draupadi', label: 'Husband', type: 'family' },
  { source: 'arjuna', target: 'drona', label: 'Student', type: 'guru' },
  { source: 'arjuna', target: 'bhima', label: 'Brother', type: 'family' },
  { source: 'arjuna', target: 'yudhishthira', label: 'Brother', type: 'family' },
  { source: 'arjuna', target: 'nakula', label: 'Brother', type: 'family' },
  { source: 'arjuna', target: 'sahadeva', label: 'Brother', type: 'family' },
  { source: 'bhima', target: 'draupadi', label: 'Husband', type: 'family' },
  { source: 'bhima', target: 'hidimba', label: 'Husband', type: 'family' },
  { source: 'bhima', target: 'duryodhana', label: 'Enemies', type: 'conflict' },
  { source: 'yudhishthira', target: 'yama', label: 'Son of', type: 'family' },
  { source: 'yudhishthira', target: 'draupadi', label: 'Husband', type: 'family' },
  { source: 'nakula', target: 'draupadi', label: 'Husband', type: 'family' },
  { source: 'sahadeva', target: 'draupadi', label: 'Husband', type: 'family' },
  { source: 'karna', target: 'duryodhana', label: 'Loyal to', type: 'alliance' },
  { source: 'karna', target: 'kunti', label: 'Son of', type: 'family' },
  { source: 'kunti', target: 'karna', label: 'Biological Mother', type: 'family' },
  { source: 'yudhishthira', target: 'kunti', label: 'Son of', type: 'family' },
  { source: 'arjuna', target: 'kunti', label: 'Son of', type: 'family' },
  { source: 'bhima', target: 'kunti', label: 'Son of', type: 'family' },
  { source: 'drona', target: 'ashwatthama', label: 'Father', type: 'family' },
  { source: 'ashwatthama', target: 'arjuna', label: 'Enemies', type: 'conflict' },
  { source: 'drona', target: 'duryodhana', label: 'Fights for', type: 'alliance' },
  { source: 'drona', target: 'ekalavya', label: 'Demanded thumb', type: 'guru' },
  { source: 'arjuna', target: 'bhishma', label: 'Defeats', type: 'conflict' },
  { source: 'bhishma', target: 'duryodhana', label: 'Fights for', type: 'alliance' },
  { source: 'vyasa', target: 'yudhishthira', label: 'Grandfather', type: 'family' },
  { source: 'vyasa', target: 'dhritarashtra', label: 'Father', type: 'family' },
  { source: 'vyasa', target: 'shuka', label: 'Father', type: 'family' },
  { source: 'ganesha', target: 'vyasa', label: 'Scribe for', type: 'divine' },
  { source: 'dhritarashtra', target: 'duryodhana', label: 'Father', type: 'family' },
  { source: 'dhritarashtra', target: 'gandhari', label: 'Husband', type: 'family' },
  { source: 'gandhari', target: 'duryodhana', label: 'Mother', type: 'family' },
  { source: 'parashurama', target: 'bhishma', label: 'Guru', type: 'guru' },
  { source: 'parashurama', target: 'drona', label: 'Guru', type: 'guru' },
  { source: 'parashurama', target: 'karna', label: 'Guru / Cursed him', type: 'guru' },
  { source: 'durvasa', target: 'kunti', label: 'Gave mantra', type: 'divine' },
  { source: 'durvasa', target: 'shakuntala', label: 'Cursed', type: 'conflict' },
  { source: 'narada', target: 'prahlada', label: 'Guru', type: 'guru' },
  { source: 'narada', target: 'brahma', label: 'Son of', type: 'family' },
  { source: 'hiranyakashipu', target: 'prahlada', label: 'Father', type: 'family' },
  { source: 'narasimha', target: 'hiranyakashipu', label: 'Slays', type: 'conflict' },
  { source: 'durga', target: 'mahishasura', label: 'Slays', type: 'conflict' },
  { source: 'kartikeya', target: 'tarakasura', label: 'Slays', type: 'conflict' },
  { source: 'indra', target: 'vritra', label: 'Slays', type: 'conflict' },
  { source: 'vishwakarma', target: 'kubera', label: 'Built Lanka for', type: 'divine' },
  { source: 'vishwakarma', target: 'krishna', label: 'Built Dwarka for', type: 'divine' },
  { source: 'yama', target: 'savitri', label: 'Wagered with', type: 'conflict' },
  { source: 'shiva', target: 'markandeya', label: 'Saved from Yama', type: 'divine' },
];

async function seed() {
  try {
    const mongoUri = process.env.MONGO_URI;
    if (!mongoUri) {
      throw new Error('MONGO_URI is not defined in environment variables');
    }

    await mongoose.connect(mongoUri);
    console.log('MongoDB connected for seeding...');

    await Character.deleteMany({});
    await Relationship.deleteMany({});

    await Character.insertMany(characters);
    await Relationship.insertMany(relationships);

    console.log(`✅ Seeded ${characters.length} characters`);
    console.log(`✅ Seeded ${relationships.length} relationships`);
    console.log('Seeding complete. Disconnecting...');
    
    await mongoose.disconnect();
    process.exit(0);
  } catch (err) {
    console.error('Seed error:', err.message);
    process.exit(1);
  }
}

seed();
